
solution = "0x2588cbfa9fda7f408b0532212c29506f8653daeae9bf278fe19899324798e578"
solution_hash = "0x2588cbfa9fda7f408b0532212c29506f8653daeae9bf278fe19899324798e578"
player_wallet = "0x2a888a2acf27b3dcf2eba36e7d0aca8ed15639d82735eedc276c66505ffd7c03"
round_id = "0x1"
